name: henlabenv
channels:
  - defaults
dependencies:
  - appnope=0.1.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.0.2=py37_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.10.15=py37_0
  - cycler=0.10.0=py37_0
  - cython=0.29=py37h0a44026_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py37_0
  - entrypoints=0.2.3=py37_2
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.2.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.4.2=py37_0
  - jedi=0.13.1=py37_0
  - jinja2=2.10=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.3=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - kiwisolver=1.0.1=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.35=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - markupsafe=1.1.0=py37h1de35cc_0
  - matplotlib=3.0.1=py37h54f8f79_0
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py37hb8a8100_0
  - mkl_random=1.0.1=py37h5d10147_1
  - nbconvert=5.3.1=py37_0
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - networkx=2.2=py37_1
  - notebook=5.7.2=py37_0
  - numpy=1.15.4=py37h6a91979_0
  - numpy-base=1.15.4=py37h8a80b8c_0
  - openssl=1.1.1a=h1de35cc_0
  - pandas=0.23.4=py37h6440ff4_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.3.1=py37_0
  - patsy=0.5.1=py37_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=18.1=py37_0
  - prometheus_client=0.4.2=py37_0
  - prompt_toolkit=2.0.7=py37_0
  - ptyprocess=0.6.0=py37_0
  - pygments=2.2.0=py37_0
  - pyparsing=2.3.0=py37_0
  - pyqt=5.9.2=py37h655552a_2
  - python=3.7.1=haf84260_3
  - python-dateutil=2.7.5=py37_0
  - pytz=2018.7=py37_0
  - pyzmq=17.1.2=py37h1de35cc_0
  - qt=5.9.6=h45cd832_2
  - qtconsole=4.4.2=py37_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.20.1=py37h4f467ca_0
  - scipy=1.1.0=py37h28f7352_1
  - seaborn=0.9.0=py37_0
  - send2trash=1.5.0=py37_0
  - setuptools=40.6.2=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.11.0=py37_1
  - sqlite=3.25.3=ha441bb4_0
  - statsmodels=0.9.0=py37h1d22016_0
  - terminado=0.8.1=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1.1=py37h1de35cc_0
  - traitlets=4.3.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - wheel=0.32.3=py37_0
  - widgetsnbextension=3.4.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=h1de35cc_3
prefix: /anaconda3/envs/henlabenv

